config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/callbacks"
  }
  resources :tasks do
    patch :log, on: :member
    patch :done, on: :member
  end
  resources :pomodoros, only: [:index, :destroy]

  root "tasks#index"
end

app/models/application_record.rb
# frozen_string_literal: true
# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pomodoro.rb
# frozen_string_literal: true

# Pomodoro
class Pomodoro < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
# frozen_string_literal: true

# Task
class Task < ApplicationRecord
  belongs_to :parent_task, optional: true, class_name: "Task"
  belongs_to :user
  has_many :pomodoros
  has_many :subtasks, source: :tasks,
                      foreign_key: :parent_task_id,
                      class_name: "Task"

  scope :main_task_of, lambda { |user_id|
    where(user_id: user_id, parent_task_id: nil)
      .order(done_flg: :asc, id: :desc)
  }

  delegate :description, to: :parent_task, prefix: true

  def self.init_with_user(params, user)
    task = new(params)
    task.user = user
    task
  end

  def add_log
    Pomodoro.create(task_id: id)
  end

  def done?
    done_flg
  end

  def subtask?
    parent_task_id?
  end
end

app/models/user.rb
# frozen_string_literal: true

# User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable, :omniauthable

  has_many :tasks
  has_many :pomodoros, through: :tasks

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
# ApplicationController
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_url, notice: "You don't have permission with this action"
  end
end

app/controllers/pomodoros_controller.rb
# frozen_string_literal: true

# PomodorosController
class PomodorosController < ApplicationController
  before_action :set_pomodoro, only: :destroy

  # GET /pomodoros
  def index
    @pomodoros = Pomodoro.all
  end

  # DELETE /pomodoros/1
  def destroy
    @pomodoro.destroy
    redirect_to pomodoros_url, notice: "Pomodoro was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pomodoro
    @pomodoro = current_user.pomodoros.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# TasksController
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update,
                                  :destroy, :log, :done]

  # GET /tasks
  def index
    @tasks = Task.main_task_of(current_user.id).includes(:subtasks)
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new(parent_task_id: parent_task_id)
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.init_with_user(task_params, current_user)

    if @task.save
      redirect_to @task, notice: "Task was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: "Task was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "Task was successfully destroyed."
  end

  # PATCH /tasks/1/log
  def log
    if @task.add_log
      redirect_to tasks_path, notice: "Pomodoro was successfully added."
    else
      redirect_to tasks_path, notice: "Pomodoro was not added."
    end
  end

  # PATCH /tasks/1/done
  def done
    if @task.toggle!(:done_flg)
      redirect_to tasks_path, notice: "Task was successfully done."
    else
      redirect_to tasks_path, notice: "Task was not done."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def parent_task_id
    return nil unless params[:parent_task_id]
    Task.find_by_id(params[:parent_task_id])&.id
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def task_params
    params
      .require(:task)
      .permit(:description, :estimated_pomodoro, :parent_task_id)
  end
end

app/controllers/users/callbacks_controller.rb
# frozen_string_literal: true
module Users
  # CallbacksController
  class CallbacksController < Devise::OmniauthCallbacksController
    def github
      @user = User.from_omniauth(request.env["omniauth.auth"])
      @user.remember_me = true
      sign_in_and_redirect @user
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
# ApplicationHelper
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTemplate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pomodoros/_form.html.erb
<%= form_for(pomodoro) do |f| %>
  <% if pomodoro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pomodoro.errors.count, "error") %> prohibited this pomodoro from being saved:</h2>

      <ul>
      <% pomodoro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %>
    <%= f.text_field :task_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pomodoros/edit.html.erb
<h1>Editing Pomodoro</h1>

<%= render 'form', pomodoro: @pomodoro %>

<%= link_to 'Show', @pomodoro %> |
<%= link_to 'Back', pomodoros_path %>

app/views/pomodoros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pomodoros</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pomodoros.each do |pomodoro| %>
      <tr>
        <td><%= pomodoro.task %></td>
        <td><%= link_to 'Show', pomodoro %></td>
        <td><%= link_to 'Destroy', pomodoro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pomodoros/new.html.erb
<h1>New Pomodoro</h1>

<%= render 'form', pomodoro: @pomodoro %>

<%= link_to 'Back', pomodoros_path %>

app/views/pomodoros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @pomodoro.task %>
</p>

<%= link_to 'Back', pomodoros_path %>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :estimated_pomodoro %>
    <%= f.number_field :estimated_pomodoro %>
  </div>

  <div class="field">
    <%= f.hidden_field :parent_task_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= task.done? ? "[x]" : link_to("[ ]", done_task_path(task), method: :patch) %>
<%= task.description %>
(Estimated: <%= task.estimated_pomodoro %>,
Logged: <%= task.pomodoros.count %>)
<% unless task.done? %>
  <%= link_to "+1", log_task_path(task), method: :patch %>
  <%= task.subtask? ? "" : link_to('Add subtask', new_task_path(parent_task_id: task)) %>
<% end %>
<%= link_to 'Edit', edit_task_path(task) %>
<%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= render "task", task: task %>
      <% if task.subtasks.present? %>
        <ul>
          <% task.subtasks.each do |subtask| %>
            <li><%= render "task", task: subtask %></li>
          <% end %>
        </ul>
      <% end %>
    </li>
    <% end %>
</ul>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Estimated pomodoro:</strong>
  <%= @task.estimated_pomodoro %>
</p>

<p>
  <strong>Done flg:</strong>
  <%= @task.done_flg %>
</p>

<% if @task.subtask? %>
<p>
  <strong>Parent task:</strong>
  <%= link_to @task.parent_task_description, @task.parent_task %>
</p>
<% end %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>